### ISSUE TITLE
Error in wss request (Secure WebSockets)

### ISSUE THREAD

**Issue by ysilvela** [Devristo/phpws#60]
When I launch the examples/echo_client.php changing the url "ws://echo.websocket.org" to "wss://echo.websocket.org" I obtain the next error. What's wrong?

2015-04-13T20:32:14+02:00 ERR (3): exception 'UnexpectedValueException' with message 'Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): this stream does not support SSL/crypto' in C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\socket-client\src\StreamEncryption.php:96

Stack trace:
#0 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\socket-client\src\StreamEncryption.php(63): React\SocketClient\StreamEncryption->toggleCrypto(Resource id #82, Object(React\Promise\Deferred), true)
#1 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\socket-client\src\StreamEncryption.php(67): React\SocketClient\StreamEncryption->React\SocketClient\{closure}()
#2 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\socket-client\src\StreamEncryption.php(38): React\SocketClient\StreamEncryption->toggle(Object(React\Stream\Stream), true)
#3 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\socket-client\src\SecureConnector.php(23): React\SocketClient\StreamEncryption->enable(Object(React\Stream\Stream))
#4 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\FulfilledPromise.php(24): React\SocketClient\SecureConnector->React\SocketClient\{closure}(Object(React\Stream\Stream))
#5 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(114): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#6 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(156): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#7 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#8 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(169): React\Promise\Promise->resolve(Object(React\Stream\Stream))
#9 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\FulfilledPromise.php(39): React\Promise\Promise->React\Promise\{closure}(Object(React\Stream\Stream))
#10 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(51): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#11 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(156): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#12 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#13 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(169): React\Promise\Promise->resolve(Object(React\Stream\Stream))
#14 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\FulfilledPromise.php(39): React\Promise\Promise->React\Promise\{closure}(Object(React\Stream\Stream))
#15 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(115): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#16 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(156): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#17 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#18 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(169): React\Promise\Promise->resolve(Resource id #82)
#19 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\FulfilledPromise.php(39): React\Promise\Promise->React\Promise\{closure}(Resource id #82)
#20 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(115): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#21 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(156): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#22 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#23 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Promise.php(169): React\Promise\Promise->resolve(Resource id #82)
#24 [internal function]: React\Promise\Promise->React\Promise\{closure}(Resource id #82)
#25 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\promise\src\Deferred.php(35): call_user_func(Object(Closure), Resource id #82)
#26 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\socket-client\src\Connector.php(72): React\Promise\Deferred->resolve(Resource id #82)
#27 [internal function]: React\SocketClient\Connector->React\SocketClient\{closure}(Resource id #82, Object(React\EventLoop\StreamSelectLoop))
#28 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\event-loop\StreamSelectLoop.php(235): call_user_func(Object(Closure), Resource id #82, Object(React\EventLoop\StreamSelectLoop))
#29 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\vendor\react\event-loop\StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#30 C:\Users\yago.silvela\Downloads\phpws-master (2)\phpws-master\examples\echo_client.php(37): React\EventLoop\StreamSelectLoop->run()
#31 {main}

**Comment by ysilvela** [comment]
The real host I need to connect via wss is "wss://www.avatarbtc.es/Routing" but I dont obtain any response.

Thanks for all devristo!!!

**Comment by coderstephen** [comment]
This issue is still occurring for me on PHP 5.6.4. Initially I thought it was related to [this issue](https://github.com/reactphp/socket-client/pull/23), but the issue was already fixed and phpws already is using react/socket-client v0.4.3, which includes a fix. I'm not 100% sure if this is an issue with phpws or a new issue for socket-client.

**Comment by coderstephen** [comment]
Turns out it is an issue with how PHPWS extends React's socket connector, which prevented it from benefitting from React's fix.

**Comment by coderstephen** [comment]
[This pull](https://github.com/Devristo/phpws/pull/69) should fix the issue, if anyone is still waiting for a fix.
