### ISSUE TITLE
Make DNS Server configurable

### ISSUE THREAD

**Issue by guckykv** [Devristo/phpws#82]
In https://github.com/Devristo/phpws/blob/master/src/Devristo/Phpws/Client/WebSocket.php 8.8.8.8 is hard coded as DNS server. Unfortunately, at my environment, I can't connect to it.

It would be nice, if I could configure which nameserver should be used.

Thx.

**Comment by Savageman** [comment]
This should be closed, since you can now use the DNS_SERVER env var to overcome this.

**Comment by guckykv** [comment]
Thx - is fixed.
